### ISSUE TITLE
pods installation fails

### ISSUE THREAD

**Issue by ennioma** [Lightstreamer/Lightstreamer-example-Chat-client-ios-swift#4]
Hi,
I'm trying to setup the project through Cocoapods but the installation fails.

Could you please tell me which version of Cocoapods should I use?

Another request directly related to this. Is it possible to install the LightStreamer iOS client 3.0 manually or using carthage?

Cheers,
Ennio

**Comment by gianlucabertani** [comment]
Hello Ennio, what kind of error are you getting from CocoaPods?

You can find download links to library and documentation at the end of this blog post:

- [blog.lightstreamer.com/2017/09/version-300-of-ios-macos-and-tvos-sdks.html](http://blog.lightstreamer.com/2017/09/version-300-of-ios-macos-and-tvos-sdks.html)

**Comment by ennioma** [comment]
Hi @gianlucabertani,
sorry for the delay.

The error installing through CP is:

```
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/ema44/.rvm/rubies/ruby-2.0.0-p648/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin16.6.0]
    RubyGems : 2.6.12
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/ema44/.rvm/rubies/ruby-2.0.0-p648/lib

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '8.0'
project 'SwiftChat.xcodeproj'

target 'SwiftChat' do
    platform :ios, '8.0'
    project 'SwiftChat.xcodeproj'
    pod 'Lightstreamer_iOS_Client', '3.0.0'
end
```

### Error

```
ArgumentError - invalid byte sequence in UTF-8
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:77:in `==='
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:77:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:33:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:132:in `write_dictionary_key_value_pair'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:149:in `block in write_dictionary'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:148:in `each'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:148:in `write_dictionary'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:112:in `write_dictionary'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:76:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:33:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:101:in `write_array_element'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:121:in `block in write_array'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:120:in `each'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:120:in `write_array'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:84:in `write_array'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:74:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:33:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:132:in `write_dictionary_key_value_pair'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:149:in `block in write_dictionary'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:148:in `each'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:148:in `write_dictionary'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:112:in `write_dictionary'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer.rb:76:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:33:in `write_object'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/nanaimo-0.2.3/lib/nanaimo/writer/xml.rb:13:in `write'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb:55:in `block in write_to_path'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb:53:in `open'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb:53:in `write_to_path'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/generator/acknowledgements/plist.rb:9:in `save_as'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:104:in `update_changed_file'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:153:in `block in create_acknowledgements'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:149:in `each'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:149:in `create_acknowledgements'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:33:in `block in install!'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:173:in `block (2 levels) in install_libraries'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:171:in `each'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:171:in `block in install_libraries'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:165:in `install_libraries'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:183:in `block in generate_pods_project'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/command/update.rb:81:in `run'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/ema44/.rvm/rubies/ruby-2.0.0-p648/bin/pod:23:in `load'
/Users/ema44/.rvm/rubies/ruby-2.0.0-p648/bin/pod:23:in `<main>'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/bin/ruby_executable_hooks:15:in `eval'
/Users/ema44/.rvm/gems/ruby-2.0.0-p648@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by gianlucabertani** [comment]
The Podfile looks correct to me, and it passes an UTF-8 charset validation. I can also install it with no errors using CocoaPods 1.3.1 and a Ruby VM 2.2.4.

I see your Ruby VM is 2.0.0, could it be the reason? Can you try again with a more recent version? Preferably 2.2.4 or greater.
